<a href="https://colab.research.google.com/github/StevenBryceLee/code-challenges/blob/master/TopologicalSort/Topological_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
"""
Topological Sort
Difficulty: Hard
Given a list of tasks and a list of dependencies return
a list of tasks in valid order. If no such order exists
return an empty array.
tasks = [1,2,3,4]
deps = [
    [2, 3],
    [2, 4],
    [4, 3],
    [1, 3],
    [1, 4],
]
topological_sort(tasks, deps) = [1,2,3,4] or [2,1,3,4]
Author: BrannanC
"""

import numpy as np
def swap(arr,idx1,idx2):
  #print('beforearr:\t',arr,idx1,idx2)
  temp = arr[idx2]
  arr[idx2] = arr[idx1]
  arr[idx1] = temp
  #print('afterarr:\t',arr)
  return arr
def topological_sort(tasks, deps):
    tasks = np.array(tasks)
    deps = np.array(deps)
    #iterate through each dependency
    for element in deps:
      #Check if the dependency is after the dependent
      if (np.where(tasks == element[0])[0][0]) > (np.where(tasks == element[1])[0][0]):
        tasks = swap(tasks,(np.where(tasks == element[0])[0][0]),(np.where(tasks == element[1])[0][0]))
        #print('tasks:\t',tasks)
    #Check if the test is satisfiable
    for element in deps:
      if (np.where(tasks == element[0])[0][0]) > (np.where(tasks == element[1])[0][0]):
        return []
    return tasks
tasks = [1,2,3,4][::-1]
deps = [
    [2, 3],
    [2, 4],
    [4, 3],
    [1, 3],
    [1, 4],
]

topological_sort(tasks, deps)

array([2, 1, 4, 3])

In [38]:
import numpy as np

In [39]:
deps = [
    [2, 3],
    [2, 4],
    [4, 3],
    [1, 3],
    [1, 4],
]
deps = np.array(deps)
print(deps)

[[2 3]
 [2 4]
 [4 3]
 [1 3]
 [1 4]]


In [40]:
set(deps[:,1])

{3, 4}

In [41]:
tasks = [1, 2, 3, 4, 5]
deps = [[1, 3], 
        [2, 3], 
        [3, 4], 
        [2, 5], 
        [5, 4]]

topological_sort(tasks, deps)

array([1, 2, 3, 5, 4])

In [42]:
tasks = [1, 2, 3, 4, 5, 6, 7, 8]
deps = [[3, 1], 
        [8, 1], 
        [8, 7], 
        [5, 7], 
        [5, 2], 
        [1, 4], 
        [1, 6], 
        [1, 2], 
        [7, 6]]
topological_sort(tasks, deps)

array([3, 5, 8, 1, 2, 7, 6, 4])

In [43]:
tasks = [1, 2, 3, 4, 5, 6, 7, 8]
deps = [[4, 2], 
      [1, 2], 
      [1, 8], 
      [6, 8], 
      [6, 3], 
      [2, 5], 
      [7, 8], 
      [2, 3], 
      [8, 7]]

topological_sort(tasks, deps)

0

In [44]:
def is_topol_ordered(ordered, tasks, deps):
    deps_graph = {}
    if len(ordered) != len(tasks):
        return False
    oSet = set()
    tSet = set()
    for i in range(len(tasks)):
        oSet.add(ordered[i])
        tSet.add(tasks[i])

    if len(oSet.difference(tSet)) != 0:
        return False

    for d in deps:
        if d[1] in deps_graph:
            deps_graph[d[1]].append(d[0])
        else:
            deps_graph[d[1]] = [d[0]]

    for t in ordered:
        if t in deps_graph and len(deps_graph[t]):
            return False
        for d in deps_graph.values():
            if t in d:
                d.remove(t)
    return True

In [53]:
def test_valid_one():
    tasks = [4, 3, 2, 1]
    deps = [
        [2, 3],
        [2, 4],
        [4, 3],
        [1, 3],
        [1, 4],
    ]
    ordered = topological_sort(tasks, deps)
    assert is_topol_ordered(ordered, tasks, deps) == True


def test_valid_two():
    tasks = [1, 2, 3, 4, 5]
    deps = [[1, 3], [2, 3], [3, 4], [2, 5], [5, 4]]
    ordered = topological_sort(tasks, deps)
    assert is_topol_ordered(ordered, tasks, deps) == True


def test_valid_three():
    tasks = [1, 2, 3, 4, 5, 6, 7, 8]
    deps = [[3, 1], [8, 1], [8, 7], [5, 7], [
        5, 2], [1, 4], [1, 6], [1, 2], [7, 6]]
    ordered = topological_sort(tasks, deps)
    assert is_topol_ordered(ordered, tasks, deps) == True


def test_invalid():
    tasks = [1, 2, 3, 4, 5, 6, 7, 8]
    deps = [[4, 2], [1, 2], [1, 8], [6, 8], [
        6, 3], [2, 5], [7, 8], [2, 3], [8, 7]]
    # No valid order
    assert len(topological_sort(tasks, deps)) == 0

In [54]:
print(test_valid_one())
print(test_valid_two())
print(test_valid_three())
print(test_invalid())

None
None
None
None


In [ ]:
#All test cases passed. 